name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - hydra-core=1.3.2
  - matplotlib
  - pandas
  - pip
  - scikit-learn
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
