name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core
  - matplotlib
  - pandas
  - pip
  - scikit-learn
  - pillow
  - pip:
      - wandb==0.16.0
      - mlflow==2.8.1
