name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib
  - pandas
  - pip
  - scikit-learn
  - pillow
  - pip:
      - wandb==0.19.1
      - mlflow==2.19.0
