name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - requests
  - scikit-learn
  - pip:
      - mlflow
      - wandb
      - git+https://github.com/DrUkachi/loan-default.git#egg=wandb-utils&subdirectory=ml_components
